name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
