name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet publish --configuration Release --no-restore --nologo --output release
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: gh-pages
          build_dir: release/wwwroot
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
